# Location of top-level MicroPython directory
MPY_DIR = ../../..

# Name of module
MOD = string

# Source files (.c or .py)
SRC = string.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = armv7m

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
